# Generated by Django 6.0.2 on 2026-02-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_vehicle_makes', models.CharField(blank=True, max_length=100, null=True)),
                ('new_rto_list', models.CharField(blank=True, max_length=100, null=True)),
                ('insurer_vertical', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_company', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=50)),
                ('sub_product', models.CharField(blank=True, max_length=50, null=True)),
                ('policy_type', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_age_min', models.IntegerField(blank=True, null=True)),
                ('vehicle_age_max', models.IntegerField(blank=True, null=True)),
                ('make_model_class', models.CharField(blank=True, max_length=150, null=True)),
                ('pi_od_rate', models.FloatField(blank=True, null=True)),
                ('pi_tp_rate', models.FloatField(blank=True, null=True)),
                ('pi_tp_2', models.FloatField(blank=True, null=True)),
                ('pi_tp_3', models.FloatField(blank=True, null=True)),
                ('pi_tp_4', models.FloatField(blank=True, null=True)),
                ('pi_tp_5', models.FloatField(blank=True, null=True)),
                ('pi_net_rate', models.FloatField(blank=True, null=True)),
                ('pi_flat_amount', models.FloatField(blank=True, null=True)),
                ('pi_vli', models.FloatField(blank=True, null=True)),
                ('pi_type', models.CharField(blank=True, max_length=50, null=True)),
                ('tariff_min', models.FloatField(blank=True, null=True)),
                ('tariff_max', models.FloatField(blank=True, null=True)),
                ('is_ncb', models.BooleanField(default=False)),
                ('is_cpa', models.BooleanField(default=False)),
                ('cc_min', models.IntegerField(blank=True, null=True)),
                ('cc_max', models.IntegerField(blank=True, null=True)),
                ('is_zd', models.BooleanField(default=False)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('sc_min', models.FloatField(blank=True, null=True)),
                ('sc_max', models.FloatField(blank=True, null=True)),
                ('veh_use', models.CharField(blank=True, max_length=50, null=True)),
                ('add_tnc', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('po_type', models.CharField(blank=True, max_length=50, null=True)),
                ('po_od_rate', models.FloatField(blank=True, null=True)),
                ('po_tp_rate', models.FloatField(blank=True, null=True)),
                ('po_net_rate', models.FloatField(blank=True, null=True)),
                ('po_flat_amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
