# Generated by Django 6.0.3 on 2026-03-10 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MakeModelClassMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MakeModelMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_model_name', models.CharField(max_length=150, unique=True)),
                ('make_model_cluster', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'insurance_productmaster',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('key_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RTOMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rto_name', models.CharField(max_length=100, unique=True)),
                ('rto_cluster', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YesNoNAMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('meaning', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GridDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer_name', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.FileField(upload_to='grid_documents/%Y/%m/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_vehicle_makes', models.CharField(blank=True, max_length=100, null=True)),
                ('new_rto_list', models.CharField(blank=True, max_length=100, null=True)),
                ('insurer_vertical', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_company', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNLOCKED', 'Unlocked'), ('LOCKED', 'Locked')], default='INACTIVE', max_length=20)),
                ('is_deleted', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('vehicle_age_min', models.FloatField(blank=True, null=True)),
                ('vehicle_age_max', models.FloatField(blank=True, null=True)),
                ('pi_od_rate', models.FloatField(blank=True, null=True)),
                ('pi_tp_rate', models.FloatField(blank=True, null=True)),
                ('pi_tp_2', models.FloatField(blank=True, null=True)),
                ('pi_tp_3', models.FloatField(blank=True, null=True)),
                ('pi_tp_4', models.FloatField(blank=True, null=True)),
                ('pi_tp_5', models.FloatField(blank=True, null=True)),
                ('pi_net_rate', models.FloatField(blank=True, null=True)),
                ('pi_flat_amount', models.FloatField(blank=True, null=True)),
                ('pi_vli', models.FloatField(blank=True, null=True)),
                ('pi_type', models.CharField(blank=True, max_length=50, null=True)),
                ('tariff_min', models.FloatField(blank=True, null=True)),
                ('tariff_max', models.FloatField(blank=True, null=True)),
                ('cc_min', models.FloatField(blank=True, null=True)),
                ('cc_max', models.FloatField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('sc_min', models.FloatField(blank=True, null=True)),
                ('sc_max', models.FloatField(blank=True, null=True)),
                ('veh_use', models.CharField(blank=True, max_length=50, null=True)),
                ('add_tnc', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('po_type', models.CharField(blank=True, max_length=50, null=True)),
                ('po_od_rate', models.FloatField(blank=True, null=True)),
                ('po_tp_rate', models.FloatField(blank=True, null=True)),
                ('po_net_rate', models.FloatField(blank=True, null=True)),
                ('po_flat_amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.fueltypemaster')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='insurance.rategroup')),
                ('make_model_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.makemodelclassmaster')),
                ('policy_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.policytypemaster')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='insurance.productmaster')),
                ('sub_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.subproductmaster')),
                ('is_cpa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpa', to='insurance.yesnonamaster')),
                ('is_ncb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncb', to='insurance.yesnonamaster')),
                ('is_zd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zd', to='insurance.yesnonamaster')),
            ],
        ),
    ]
