# Generated by Django 6.0.2 on 2026-03-10 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MISFieldMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100, unique=True)),
                ('field_label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['field_label'],
            },
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='is_cpa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpa', to='insurance.yesnonamaster'),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='is_ncb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncb', to='insurance.yesnonamaster'),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='is_zd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zd', to='insurance.yesnonamaster'),
        ),
        migrations.CreateModel(
            name='PolicyDocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='policy_uploads/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('extraction_method', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('parsed_json', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyMISRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insured_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_make_model', models.CharField(blank=True, max_length=255, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cubic_capacity_cc', models.CharField(blank=True, max_length=50, null=True)),
                ('gross_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('policy_start_date', models.DateField(blank=True, null=True)),
                ('policy_end_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('rto_location', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_ai_json', models.JSONField(blank=True, null=True)),
                ('confidence_notes', models.TextField(blank=True, null=True)),
                ('ai_model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mis_record', to='insurance.policydocumentupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MISFieldAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('field_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='insurance.misfieldmaster')),
            ],
            options={
                'ordering': ['field_master__field_label', 'alias_text'],
                'unique_together': {('field_master', 'alias_text')},
            },
        ),
    ]
