# Generated by Django 6.0.2 on 2026-02-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratemaster',
            name='is_cpa',
            field=models.CharField(default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='is_ncb',
            field=models.CharField(default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='is_zd',
            field=models.CharField(default='NA', max_length=3),
        ),
    ]
