# Generated by Django 6.0.2 on 2026-02-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
