# Generated by Django 6.0.2 on 2026-02-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_rategroup_group_ratemaster_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rategroup',
            name='group',
        ),
    ]
