# Generated by Django 6.0.2 on 2026-03-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_misfieldmaster_alter_ratemaster_is_cpa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policydocumentupload',
            old_name='file',
            new_name='uploaded_file',
        ),
        migrations.AlterField(
            model_name='policydocumentupload',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
    ]
