# Generated by Django 6.0.2 on 2026-02-12 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_ratemaster_is_cpa_alter_ratemaster_is_ncb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesNoNAMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('meaning', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='is_cpa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpa', to='insurance.yesnonamaster'),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='is_ncb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncb', to='insurance.yesnonamaster'),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='is_zd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zd', to='insurance.yesnonamaster'),
        ),
    ]
