# Generated by Django 6.0.2 on 2026-03-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_rename_file_policydocumentupload_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='griddocument',
            options={'ordering': ['-uploaded_date']},
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='new_rto_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='new_vehicle_makes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
