# Generated by Django 6.0.2 on 2026-02-18 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_remove_rategroup_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratemaster',
            name='mpg_id',
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='group',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='insurance.rategroup'),
        ),
    ]
