# Generated by Django 6.0.2 on 2026-03-11 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_alter_auditlog_options_alter_griddocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratemaster',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='LockedPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=50)),
                ('policy_holder_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_company', models.CharField(blank=True, max_length=255, null=True)),
                ('po_type', models.CharField(blank=True, max_length=50, null=True)),
                ('po_rate', models.FloatField(blank=True, null=True)),
                ('po_flat_amount', models.FloatField(blank=True, null=True)),
                ('add_tnc', models.TextField(blank=True, null=True)),
                ('rto_code', models.CharField(blank=True, max_length=50, null=True)),
                ('make_name', models.CharField(blank=True, max_length=150, null=True)),
                ('fuel', models.CharField(blank=True, max_length=50, null=True)),
                ('cc', models.CharField(blank=True, max_length=50, null=True)),
                ('sc', models.CharField(blank=True, max_length=50, null=True)),
                ('mfg_year', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked')], default='UNLOCKED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_policies', to=settings.AUTH_USER_MODEL)),
                ('source_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_policies', to='insurance.ratemaster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
