# Generated by Django 6.0.2 on 2026-02-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_remove_ratemaster_mpg_id_alter_ratemaster_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeModelMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_model_name', models.CharField(max_length=150, unique=True)),
                ('make_model_cluster', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RTOMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rto_name', models.CharField(max_length=100, unique=True)),
                ('rto_cluster', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
