# Generated by Django 6.0.2 on 2026-02-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_makemodelmaster_rtomaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makemodelmaster',
            name='make_model_cluster',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='rtomaster',
            name='rto_cluster',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
