# Generated by Django 6.0.2 on 2026-03-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_alter_ratemaster_status_lockedpolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makemodelmaster',
            options={'ordering': ['make_model_name']},
        ),
        migrations.AlterModelOptions(
            name='ratemaster',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='rtomaster',
            options={'ordering': ['rto_name']},
        ),
        migrations.AlterUniqueTogether(
            name='lockedpolicy',
            unique_together={('source_rate', 'vehicle_no', 'policy_holder_name')},
        ),
    ]
