# Generated by Django 6.0.2 on 2026-03-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_alter_makemodelmaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='griddocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FOLLOW-UP', 'Follow-up'), ('DONE', 'Done')], default='PENDING', max_length=20),
        ),
    ]
