# Generated by Django 6.0.2 on 2026-02-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_alter_makemodelmaster_make_model_cluster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makemodelmaster',
            name='make_model_cluster',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='cc_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='cc_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='vehicle_age_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='vehicle_age_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtomaster',
            name='rto_cluster',
            field=models.TextField(blank=True, null=True),
        ),
    ]
