# Generated by Django 6.0.2 on 2026-03-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_alter_makemodelmaster_make_model_cluster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratemaster',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=20),
        ),
    ]
