# Generated by Django 6.0.2 on 2026-03-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_ratemaster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratemaster',
            name='is_deleted',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10),
        ),
    ]
