# Generated by Django 6.0.2 on 2026-04-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_mappingconfiguration_misfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MappingConfiguration',
        ),
        migrations.DeleteModel(
            name='MISFile',
        ),
    ]
