# Generated by Django 6.0.2 on 2026-04-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_delete_mappingconfiguration_delete_misfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Base', help_text='e.g., Base, Motor, Health', max_length=50)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('field_name', models.CharField(max_length=150, unique=True)),
                ('has_dropdown', models.BooleanField(default=False)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('extraction_method', models.CharField(choices=[('AI', 'AI Read'), ('MANUAL', 'Manual')], default='AI', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='FieldSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym_text', models.CharField(max_length=255)),
                ('extraction_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='insurance.extractionfield')),
            ],
            options={
                'unique_together': {('extraction_field', 'synonym_text')},
            },
        ),
        migrations.DeleteModel(
            name='MISFieldAlias',
        ),
        migrations.DeleteModel(
            name='MISFieldMaster',
        ),
    ]
