# Generated by Django 6.0.2 on 2026-04-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_extractionfield_fieldsynonym_delete_misfieldalias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionfield',
            name='dropdown_options',
            field=models.TextField(blank=True, help_text='Comma-separated list of options (e.g., HDFC, ICICI, Tata)', null=True),
        ),
    ]
