# Generated by Django 6.0.2 on 2026-06-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='policymisrecord',
            name='actual_payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='policymisrecord',
            name='expected_payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='policymisrecord',
            name='reconciliation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MATCH', 'Match'), ('DISCREPANCY', 'Discrepancy')], default='PENDING', max_length=20),
        ),
    ]
