# Generated by Django 6.0.2 on 2026-06-25 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_policymisrecord_actual_payout_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mis_column_name', models.CharField(help_text="Exact column header from the raw MIS CSV (e.g., 'Policy: rto city', 'Policy: cc cubic capacity')", max_length=255)),
                ('grid_field_name', models.CharField(help_text="Corresponding field in the RateMaster model (e.g., 'new_rto_list', 'cc_range')", max_length=255)),
                ('mapping_type', models.CharField(choices=[('EXACT', 'Exact Match (e.g., Product, Sub Product, Insurer)'), ('CONTAINS', 'Contains / CSV Match (e.g., RTO Cluster, Vehicle Make)'), ('RANGE_CC', 'CC Range Bound Match'), ('RANGE_SC', 'Seating Capacity Range Bound Match'), ('RANGE_DATE', 'Registration/Inception Date Bound Match'), ('RANGE_AGE', 'Vehicle Age Bound Match')], default='EXACT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order_index', 'mis_column_name'],
            },
        ),
        migrations.CreateModel(
            name='MISFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='mis_uploads/%Y/%m/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='mis_processed/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
