# Generated by Django 6.0.2 on 2026-06-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0014_mappingconfiguration_misfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mappingconfiguration',
            options={'ordering': ['order_index', 'source_column']},
        ),
        migrations.RemoveField(
            model_name='mappingconfiguration',
            name='grid_field_name',
        ),
        migrations.RemoveField(
            model_name='mappingconfiguration',
            name='mapping_type',
        ),
        migrations.RemoveField(
            model_name='mappingconfiguration',
            name='mis_column_name',
        ),
        migrations.AddField(
            model_name='mappingconfiguration',
            name='operator',
            field=models.CharField(choices=[('EXACT', 'Equals (Exact Match)'), ('CONTAINS', 'Contains / CSV Match (e.g. RTO in Cluster)'), ('RANGE_CC', 'CC Range Bound Match'), ('RANGE_SC', 'Seating Capacity Range Bound Match'), ('RANGE_DATE', 'Date Range Bound Match'), ('RANGE_AGE', 'Vehicle Age Bound Match')], default='EXACT', max_length=20),
        ),
        migrations.AddField(
            model_name='mappingconfiguration',
            name='source_column',
            field=models.CharField(default='', help_text='Left operand column', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mappingconfiguration',
            name='source_table',
            field=models.CharField(choices=[('MIS_File', 'MIS File (Uploaded Data)'), ('RateMaster', 'Rate Master (Grid Data)')], default='MIS_File', help_text='Left operand table', max_length=100),
        ),
        migrations.AddField(
            model_name='mappingconfiguration',
            name='target_column',
            field=models.CharField(default='', help_text='Right operand column', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mappingconfiguration',
            name='target_table',
            field=models.CharField(choices=[('MIS_File', 'MIS File (Uploaded Data)'), ('RateMaster', 'Rate Master (Grid Data)')], default='RateMaster', help_text='Right operand table', max_length=100),
        ),
    ]
