# Generated by Django 6.0.2 on 2026-06-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_alter_mappingconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingconfiguration',
            name='operator',
            field=models.CharField(choices=[('EXACT', 'Equals (Exact Match)'), ('WORD_MATCH', 'Word Match (Whole Word / Exact List Item)'), ('CONTAINS', 'Contains (Substring Match)'), ('RANGE_CC', 'CC Range Bound Match'), ('RANGE_SC', 'Seating Capacity Range Bound Match'), ('RANGE_DATE', 'Date Range Bound Match'), ('RANGE_AGE', 'Vehicle Age Bound Match')], default='EXACT', max_length=20),
        ),
        migrations.AlterField(
            model_name='mappingconfiguration',
            name='source_column',
            field=models.CharField(blank=True, default='', help_text='Left operand column', max_length=255),
        ),
        migrations.AlterField(
            model_name='mappingconfiguration',
            name='target_column',
            field=models.CharField(blank=True, default='', help_text='Right operand column', max_length=255),
        ),
    ]
