# Generated by Django 6.0.2 on 2026-07-17 12:16

import random

from django.db import migrations, models


def backfill_user_id_codes(apps, schema_editor):
    UserProfile = apps.get_model('insurance', 'UserProfile')
    User = apps.get_model('auth', 'User')

    existing_codes = set(
        UserProfile.objects.exclude(user_id_code__isnull=True)
        .exclude(user_id_code='')
        .values_list('user_id_code', flat=True)
    )

    def next_code():
        while True:
            candidate = f"{random.randint(0, 9999):04d}"
            if candidate not in existing_codes:
                existing_codes.add(candidate)
                return candidate

    # Every User gets a profile (some legacy accounts predate UserProfile),
    # and every profile gets a unique 4-digit code if it doesn't have one yet.
    for user in User.objects.all():
        profile, _ = UserProfile.objects.get_or_create(user=user)
        if not profile.user_id_code:
            profile.user_id_code = next_code()
            profile.save(update_fields=['user_id_code'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0017_userprofile_agent_type_userprofile_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.RunPython(backfill_user_id_codes, noop),
    ]
