# Generated by Django 6.0.2 on 2026-07-20 07:07
#
# Hand-converted to CREATE INDEX CONCURRENTLY: a plain AlterField/AddIndex on
# a live table takes a lock for the duration of the index build, which blocks
# writes — including the bulk MIS/rate uploads this app does regularly.
# CONCURRENTLY avoids that at the cost of a slower build and can't run inside
# a transaction, hence atomic = False on the whole migration.
#
# Each CREATE/DROP INDEX CONCURRENTLY is its own RunSQL operation rather than
# combined into fewer multi-statement strings — Postgres requires CONCURRENTLY
# to be the only statement executed in its command, so bundling it with
# anything else in one execute() call would fail. state_operations mirrors
# what the original autogenerated AlterField/AddIndex operations recorded, so
# Django's model state (and future makemigrations runs) sees the same result
# either way — only how the DDL is actually issued differs.
#
# Note: this migration is Postgres-only. It will fail if ever run against the
# SQLite fallback in project/settings.py (only reachable when neither
# DATABASE_URL nor DB_NAME is set) — CONCURRENTLY and varchar_pattern_ops are
# both Postgres-specific. Production and any Postgres-backed dev environment
# are unaffected.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('insurance', '0018_alter_userprofile_user_id_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- ratemaster.insurance_company ---
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "insurance_ratemaster_insurance_company_70a49c34" '
                'ON "insurance_ratemaster" ("insurance_company");',
            reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "insurance_ratemaster_insurance_company_70a49c34";',
            state_operations=[
                migrations.AlterField(
                    model_name='ratemaster',
                    name='insurance_company',
                    field=models.CharField(db_index=True, max_length=100),
                ),
            ],
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "insurance_ratemaster_insurance_company_70a49c34_like" '
                'ON "insurance_ratemaster" ("insurance_company" varchar_pattern_ops);',
            reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "insurance_ratemaster_insurance_company_70a49c34_like";',
        ),

        # --- ratemaster.is_deleted ---
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "insurance_ratemaster_is_deleted_844b4b84" '
                'ON "insurance_ratemaster" ("is_deleted");',
            reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "insurance_ratemaster_is_deleted_844b4b84";',
            state_operations=[
                migrations.AlterField(
                    model_name='ratemaster',
                    name='is_deleted',
                    field=models.CharField(
                        choices=[('YES', 'Yes'), ('NO', 'No')], db_index=True, default='NO', max_length=10
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "insurance_ratemaster_is_deleted_844b4b84_like" '
                'ON "insurance_ratemaster" ("is_deleted" varchar_pattern_ops);',
            reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "insurance_ratemaster_is_deleted_844b4b84_like";',
        ),

        # --- ratemaster.status ---
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "insurance_ratemaster_status_67d7b67c" '
                'ON "insurance_ratemaster" ("status");',
            reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "insurance_ratemaster_status_67d7b67c";',
            state_operations=[
                migrations.AlterField(
                    model_name='ratemaster',
                    name='status',
                    field=models.CharField(
                        choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True,
                        default='INACTIVE', max_length=20
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "insurance_ratemaster_status_67d7b67c_like" '
                'ON "insurance_ratemaster" ("status" varchar_pattern_ops);',
            reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "insurance_ratemaster_status_67d7b67c_like";',
        ),

        # --- lockedpolicy.vehicle_no (explicit Meta.indexes entry, no _like variant) ---
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "insurance_l_vehicle_256108_idx" '
                'ON "insurance_lockedpolicy" ("vehicle_no");',
            reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "insurance_l_vehicle_256108_idx";',
            state_operations=[
                migrations.AddIndex(
                    model_name='lockedpolicy',
                    index=models.Index(fields=['vehicle_no'], name='insurance_l_vehicle_256108_idx'),
                ),
            ],
        ),
    ]
