# Generated by Django 6.0.2 on 2026-07-22 05:35
#
# Hand-converted to CREATE INDEX CONCURRENTLY (same reasoning as migration
# 0019 — avoids locking the table against concurrent bulk uploads) and to
# explicit DESC NULLS LAST on every column. Django's own AddIndex generates
# plain DESC, which Postgres defaults to NULLS FIRST — that doesn't match
# the .desc(nulls_last=True) ordering actually used by motor_payout_rates
# and policy_lock_checker, so the plan-time null ordering has to be spelled
# out for the index to be usable for that exact ORDER BY without Postgres
# still having to re-sort.

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('insurance', '0019_add_hot_path_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                'CREATE INDEX CONCURRENTLY IF NOT EXISTS "ratemaster_payout_sort_idx" '
                'ON "insurance_ratemaster" ('
                '"po_net_rate" DESC NULLS LAST, '
                '"po_od_rate" DESC NULLS LAST, '
                '"po_flat_amount" DESC NULLS LAST, '
                '"id" DESC'
                ');'
            ),
            reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "ratemaster_payout_sort_idx";',
            state_operations=[
                migrations.AddIndex(
                    model_name='ratemaster',
                    index=models.Index(
                        fields=['-po_net_rate', '-po_od_rate', '-po_flat_amount', '-id'],
                        name='ratemaster_payout_sort_idx',
                    ),
                ),
            ],
        ),
    ]
