# Generated by Django 6.0.2 on 2026-07-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0021_seed_page_access_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company', models.CharField(db_index=True, max_length=255)),
                ('product_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('policy_category', models.CharField(blank=True, max_length=20, null=True)),
                ('plan_names', models.TextField(blank=True, null=True)),
                ('business_type', models.CharField(blank=True, max_length=20, null=True)),
                ('min_deductible', models.FloatField(blank=True, null=True)),
                ('max_deductible', models.FloatField(blank=True, null=True)),
                ('min_sum_insured', models.FloatField(blank=True, null=True)),
                ('max_sum_insured', models.FloatField(blank=True, null=True)),
                ('min_age', models.FloatField(blank=True, null=True)),
                ('max_age', models.FloatField(blank=True, null=True)),
                ('pincode_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('payin_rate', models.FloatField(blank=True, null=True)),
                ('one_year_rate', models.FloatField(blank=True, null=True)),
                ('multi_year_2_rate', models.FloatField(blank=True, null=True)),
                ('multi_year_3_rate', models.FloatField(blank=True, null=True)),
                ('multi_year_4_rate', models.FloatField(blank=True, null=True)),
                ('multi_year_5_rate', models.FloatField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_deleted', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], db_index=True, default='NO', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['insurance_company', 'product_name'], name='healthrate_insurer_prod_idx')],
            },
        ),
    ]
