# Generated by Django 6.0.2 on 2026-07-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0022_add_health_rate_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthratemaster',
            name='source_row_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
