# Generated by Django 6.0.2 on 2026-07-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0024_add_pincode_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('MOTOR', 'Motor'), ('HEALTH', 'Health'), ('LIFE', 'Life')], db_index=True, default='MOTOR', max_length=20),
        ),
    ]
