# Generated by Django 6.0.2 on 2026-07-27 12:50

from django.db import migrations

# Keys that only ever appear in a ticket raised from the Health Points
# Checker (health_payout_rates.html's submitTicket()) — Motor's Quote
# Simulator never sends any of these. New tickets from either page now send
# category explicitly; this is a one-time backfill for tickets raised before
# that existed, when every ticket came from Motor except ones that happened
# to be raised from the brand-new Health page.
HEALTH_MARKER_KEYS = {"Sum Assured", "Plan Type", "Policy Term", "Eldest Member Age", "Pincode"}


def backfill_category(apps, schema_editor):
    SupportTicket = apps.get_model('insurance', 'SupportTicket')
    for ticket in SupportTicket.objects.all():
        payload = ticket.form_payload or {}
        if HEALTH_MARKER_KEYS.intersection(payload.keys()):
            ticket.category = "HEALTH"
            ticket.save(update_fields=["category"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0025_add_supportticket_category'),
    ]

    operations = [
        migrations.RunPython(backfill_category, noop),
    ]
