# Generated by Django 6.0.2 on 2026-07-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0028_specialraterequest_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='misfile',
            name='coverage_gaps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
