# Generated by Django 6.0.2 on 2026-08-03 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0031_specialraterequest_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='misfile',
            name='health_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MISFailedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('status_key', models.CharField(choices=[('MULTIPLE_MATCHES', '⚠️ Multiple Matches'), ('NO_MATCH', '❌ No Match'), ('BAD_DATA', 'Failed - Bad Data'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('mapping_status', models.CharField(max_length=50)),
                ('failure_reason', models.TextField()),
                ('group_ids', models.JSONField(blank=True, default=list)),
                ('insurer', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mis_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_rows', to='insurance.misfile')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('mis_file', 'row_id'), name='uniq_mis_failed_row')],
            },
        ),
    ]
