# Generated by Django 6.0.2 on 2026-08-29 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0032_mis_failed_row'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateOverlapScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='RUNNING', max_length=20)),
                ('groups_scanned', models.IntegerField(default=0)),
                ('pairs_found', models.IntegerField(default=0)),
                ('type_counts', models.JSONField(blank=True, default=dict)),
                ('capped_types', models.JSONField(blank=True, default=list)),
                ('was_capped', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_overlap_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RateOverlapPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('group_key_a', models.IntegerField()),
                ('group_key_b', models.IntegerField()),
                ('conflict_type', models.CharField(choices=[('EXACT_DUPLICATE', 'Exact Duplicate'), ('CONTAINED', 'Contained Range'), ('OPEN_ENDED', 'Open-Ended Overlap'), ('PARTIAL', 'Partial Overlap')], db_index=True, max_length=20)),
                ('severity_rank', models.IntegerField(default=4)),
                ('row_count_a', models.IntegerField(default=0)),
                ('row_count_b', models.IntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='insurance.rateoverlapscan')),
            ],
            options={
                'ordering': ['severity_rank', 'insurance_company', 'group_key_a', 'group_key_b'],
                'constraints': [models.UniqueConstraint(fields=('scan', 'group_key_a', 'group_key_b'), name='uniq_rate_overlap_pair')],
            },
        ),
    ]
