# Generated by Django 6.0.2 on 2026-08-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0033_rateoverlapscan_rateoverlappair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateoverlappair',
            name='conflict_type',
            field=models.CharField(choices=[('EXACT_DUPLICATE', 'Exact Duplicate'), ('TNC_VARIANT', 'Same Rules, Different T&C'), ('CONTAINED', 'Contained Range'), ('OPEN_ENDED', 'Open-Ended Overlap'), ('PARTIAL', 'Partial Overlap')], db_index=True, max_length=20),
        ),
    ]
