# Generated by Django 6.0.2 on 2026-08-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0034_alter_rateoverlappair_conflict_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateoverlapscan',
            name='tnc_only_skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rateoverlappair',
            name='conflict_type',
            field=models.CharField(choices=[('EXACT_DUPLICATE', 'Exact Duplicate'), ('CONTAINED', 'Contained Range'), ('OPEN_ENDED', 'Open-Ended Overlap'), ('PARTIAL', 'Partial Overlap')], db_index=True, max_length=20),
        ),
    ]
