# Generated by Django 6.0.2 on 2026-08-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0035_rateoverlapscan_tnc_only_skipped_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateoverlapscan',
            name='tnc_only_skipped',
        ),
        migrations.AddField(
            model_name='rateoverlapscan',
            name='tnc_differing_skipped',
            field=models.IntegerField(default=0),
        ),
    ]
