# Generated by Django 6.0.2 on 2026-08-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0036_remove_rateoverlapscan_tnc_only_skipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateoverlappair',
            name='conflict_type',
            field=models.CharField(choices=[('DOUBLE_RATE_RISK', 'Double Rate Risk'), ('EXACT_DUPLICATE', 'Exact Duplicate'), ('CONTAINED', 'Contained Range'), ('OPEN_ENDED', 'Open-Ended Overlap'), ('PARTIAL', 'Partial Overlap')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rateoverlappair',
            name='severity_rank',
            field=models.IntegerField(default=5),
        ),
    ]
