# Generated by Django 6.0.2 on 2026-08-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0037_alter_rateoverlappair_conflict_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateoverlapscan',
            name='filter_as_of_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rateoverlapscan',
            name='filter_insurer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
