# Generated by Django 6.0.2 on 2026-08-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0038_rateoverlapscan_filter_as_of_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateoverlapscan',
            name='filter_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
