# Generated by Django 6.0.2 on 2026-09-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0039_rateoverlapscan_filter_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='griddocument',
            name='work_effected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
