# Generated by Django 6.0.2 on 2026-09-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0040_grid_document_work_effected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='griddocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FOLLOW-UP', 'Follow-up'), ('DONE', 'Done'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
