# Generated by Django 6.0.2 on 2026-09-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0041_alter_griddocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratemaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
