# Generated by Django 6.0.2 on 2026-09-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0042_add_ratemaster_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('WRONG_RATE', 'Wrong Rate'), ('DOUBLE_RATE', 'Double Rate'), ('MISSING_RATE', 'Missing Rate'), ('OTHERS', 'Others')], default='', max_length=20),
        ),
    ]
