# Generated by Django 6.0.2 on 2026-09-16 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0044_seed_missing_make_model_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingMakeModelManualResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('product', models.CharField(blank=True, max_length=100)),
                ('sub_product', models.CharField(blank=True, max_length=100)),
                ('insurer', models.CharField(blank=True, max_length=150)),
                ('vehicle_class', models.CharField(blank=True, max_length=150)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('value', 'product', 'sub_product', 'insurer', 'vehicle_class')},
            },
        ),
    ]
