# Generated by Django 6.0.2 on 2026-10-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0050_makemodelmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridArchiveBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, help_text='First day of the month that was archived.')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('documents_archived', models.PositiveIntegerField(default=0)),
                ('files_archived', models.PositiveIntegerField(default=0)),
                ('bytes_archived', models.PositiveBigIntegerField(default=0)),
                ('manifest_key', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
