# Generated by Django 6.0.2 on 2026-02-17 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTypeMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MakeModelClassMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyTypeMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubProductMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YesNoNAMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('meaning', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_vehicle_makes', models.CharField(blank=True, max_length=100, null=True)),
                ('new_rto_list', models.CharField(blank=True, max_length=100, null=True)),
                ('insurer_vertical', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_company', models.CharField(max_length=100)),
                ('vehicle_age_min', models.IntegerField(blank=True, null=True)),
                ('vehicle_age_max', models.IntegerField(blank=True, null=True)),
                ('pi_od_rate', models.FloatField(blank=True, null=True)),
                ('pi_tp_rate', models.FloatField(blank=True, null=True)),
                ('pi_tp_2', models.FloatField(blank=True, null=True)),
                ('pi_tp_3', models.FloatField(blank=True, null=True)),
                ('pi_tp_4', models.FloatField(blank=True, null=True)),
                ('pi_tp_5', models.FloatField(blank=True, null=True)),
                ('pi_net_rate', models.FloatField(blank=True, null=True)),
                ('pi_flat_amount', models.FloatField(blank=True, null=True)),
                ('pi_vli', models.FloatField(blank=True, null=True)),
                ('pi_type', models.CharField(blank=True, max_length=50, null=True)),
                ('tariff_min', models.FloatField(blank=True, null=True)),
                ('tariff_max', models.FloatField(blank=True, null=True)),
                ('cc_min', models.IntegerField(blank=True, null=True)),
                ('cc_max', models.IntegerField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('sc_min', models.FloatField(blank=True, null=True)),
                ('sc_max', models.FloatField(blank=True, null=True)),
                ('veh_use', models.CharField(blank=True, max_length=50, null=True)),
                ('add_tnc', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('po_type', models.CharField(blank=True, max_length=50, null=True)),
                ('po_od_rate', models.FloatField(blank=True, null=True)),
                ('po_tp_rate', models.FloatField(blank=True, null=True)),
                ('po_net_rate', models.FloatField(blank=True, null=True)),
                ('po_flat_amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fuel_type', models.ForeignKey(blank=True, db_column='fuel_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.fueltypemaster')),
                ('make_model_class', models.ForeignKey(blank=True, db_column='make_model_class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.makemodelclassmaster')),
                ('policy_type', models.ForeignKey(blank=True, db_column='policy_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.policytypemaster')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='insurance.productmaster', to_field='code')),
                ('sub_product', models.ForeignKey(blank=True, db_column='sub_product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.subproductmaster')),
                ('is_cpa', models.ForeignKey(db_column='is_cpa_id', on_delete=django.db.models.deletion.CASCADE, related_name='cpa', to='insurance.yesnonamaster')),
                ('is_ncb', models.ForeignKey(db_column='is_ncb_id', on_delete=django.db.models.deletion.CASCADE, related_name='ncb', to='insurance.yesnonamaster')),
                ('is_zd', models.ForeignKey(db_column='is_zd_id', on_delete=django.db.models.deletion.CASCADE, related_name='zd', to='insurance.yesnonamaster')),
            ],
        ),
    ]
