# Generated by Django 6.0.2 on 2026-02-17 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_productmaster_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmaster',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='insurance.productmaster'),
        ),
        migrations.CreateModel(
            name='RateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('key_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.rategroup')),
            ],
        ),
    ]
