# Generated by Django 6.0.2 on 2026-02-12 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_yesnonamaster_alter_ratemaster_is_cpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='is_cpa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpa', to='insurance.yesnonamaster'),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='is_ncb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ncb', to='insurance.yesnonamaster'),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='is_zd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zd', to='insurance.yesnonamaster'),
        ),
        migrations.AlterField(
            model_name='ratemaster',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.productmaster'),
        ),
    ]
